import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Appbar } from "@/components/Appbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body>
        <ThemeProvider defaultTheme="dark" attribute='class' forcedTheme="dark">
          <Appbar/>
        {children}
        </ThemeProvider>
      </body>
      </ClerkProvider>
    </html>
  );
}
